name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
           curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
           curl -fsSL https://code-server.dev/install.sh | sh
           timeout 2s code-server
           %cd ~/.config/code-server
           mv config.yaml llod
           wget https://raw.githubusercontent.com/WhynotSir/tt/main/config.yaml 
           npm install -g localtunnel
           code-server --link
